print(3+4)
print(3-4)
print(3*4)
print(3/4)
print(3**4)
print(3//4)
print(3%4)
print("your name")
print("your age")
print("your country")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh', 'python','finland']))
print(type("your name"))
print(type("Your family name"))
print(type("Your country"))